# parameters: {}
# environment: {}
packages:
    - name: api
      shared: false
      functions:
        - name: status
          binary: false
          main: ""
          runtime: go:1.25
          web: true
        - name: dns
          binary: false
          main: ""
          runtime: go:1.25
          web: true
