# parameters: {}
# environment: {}
packages:
    - name: api
      shared: false
      environment:
        DO_TOKEN: "${DO_TOKEN}"
        INSTANCE_SSH_KEY: "${INSTANCE_SSH_KEY}"
        INSTANCE_SIZE: "${INSTANCE_SIZE}"
        INSTANCE_NAME: "${INSTANCE_NAME}"
        INSTANCE_VOLUME_ID: "${INSTANCE_VOLUME_ID}"
        INSTANCE_VOLUME_NAME: "${INSTANCE_VOLUME_NAME}"
        INSTANCE_REGION: "${INSTANCE_REGION}"
        ITZG_ENV: "${ITZG_ENV}"
        SERVER_DOMAIN: "${SERVER_DOMAIN}"
        DOMAIN: "${DOMAIN}"
        FUNCTIONS_URL: "${FUNCTIONS_URL}"
        FUNCTIONS_PASSWORD: "${FUNCTIONS_PASSWORD}"
        FUNCTIONS_PASSWORD_HASH: "${FUNCTIONS_PASSWORD_HASH}"
        AUTO_DESTROY: "${AUTO_DESTROY}"
        RECORD_ID: "${RECORD_ID}"
      functions:
        - name: status
          binary: false
          main: ""
          runtime: go:1.25
          web: true
        - name: dns
          binary: false
          main: ""
          runtime: go:1.25
          web: true
